### ISSUE TITLE
ArgumentError::invalid byte sequence in UTF-8, Duration: 0.179 seconds

### ISSUE THREAD

**Issue by keesma** [skoona/HomieMonitor#7] opened 2020-04-02 23:33 UTC
I have an issue that is similar to issue #4. 
I get the error ArgumentError::invalid byte sequence in UTF-8, Duration: 0.179 seconds when discovering devices. This error is probably related to degrees symbol in several mqtt topics. However this degrees symbol is presented by 0xC2 0xB0, which is a normai UTF-8 symbol.
Why is this error generated and what can I do to solve it? 

The log of the mqtt topics in attached.
[mqqt.log](https://github.com/skoona/HomieMonitor/files/4424279/mqqt.log)

**Comment by skoona** [comment] 2020-05-30 18:02
I am researching a fix for this.  So far each report of this nature has been resolved by replacing the offending chars, and often the degree symbol has been the cause.  You however, know the proper utf-8 values for it, so I'll dig a little deeper.  StandBy.

**Comment by skoona** [comment] 2020-05-31 04:07
I believe Release 0.9.0 will resolve this issue by converting the invalid char to a question mark or a period.  Homie recommends that all transported values be string chars, and I assumed that to mean UTF-8.  When binary data is in the payload these exceptions are raised and thus far cannot be intercepted, as there is not guarantee that the binary data will map to UTF.  

Identifying the invalid char and replacing it at the source is the only course of action.

**Closed by skoona** 2020-05-31 04:07 UTC
